#开发环境
server:
  port: 80

  servlet:
    context-path:

spring:
  #数据库地址
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 2167137570legacy
    url: jdbc:mysql://192.168.71.128/Myblog?useSSL=false&useServerPrepStmts=TRUE
    driver-class-name: com.mysql.cj.jdbc.Driver

#  redis:
#    host: 192.168.71.128
#    port: 6379
#    connect-timeout: 5000