spring:
  #环境
  profiles:
    active: dev
#    active: prod

  application:
    name: Myblog
    
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

#日志
logging:
  level:
    root: info
