spring:
  #环境
  profiles:
    active: dev
#    active: prod

  application:
    name: Myblog
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
#日志
logging:
  level:
    java: off
    javax: off
    io: off
    sun: off
    _org: off
    reactor: off
    org.apache: off
#    org.springframework: off
    org.mybatis: off
    org.aspectj: off
    springfox: off