#测试环境
server:
  port: 8080

spring:
  config:
    name: test
  #数据库地址
  datasource:
    druid:
      username: root
      password: 2167137570legacy
      url: jdbc:mysql://localhost/Myblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver

#地址
URL: http://10.26.186.247:8080

#mp配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.www.augenstern.entity.dao.*
  mapper-locations: classpath:mapper/*.xml

#缓存技术 jetCache
jetcache:
  statIntervalMinutes: 1  #每个一分钟显示统计数据
  #本地方案
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson    #转key字符串
      limit: 100  #最大数目

  #远程方案
  remote:
    default:    #默认配置
      keyConvertor: fastjson
      type: redis       # 配置redis
      host: localhost
      port: 6379
      poolConfig:
        maxTotal: 50    #最大连接数
