spring:
  #环境
  profiles:
#    active: dev
    active: prod
#    active: test

  application:
    name: CycleDR的小站
    
  mvc:
    path match:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

#日志
logging:
  level:
    root: info
