#生产环境
server:
  #ssl
  port: 443
  ssl:
    enabled: true
    key-store: classpath:ssl/wzxaugenstern.online.jks
    key-store-password: 2167137570legacy
    keyStoreType: JKS

  servlet:
    context-path:

spring:
  #数据库地址
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 2167137570legacy
    url: jdbc:mysql://127.0.0.1:3306/Myblog?useSSL=false&useServerPrepStmts=TRUE
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    connect-timeout: 5000

#转发端口
http-port: 80