spring:
  #环境
  profiles:
    active: dev
#    active: prod


  #数据库地址
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 2167137570legacy
    url: jdbc:mysql://127.0.0.1:3306/Myblog?useSSL=false&useServerPrepStmts=TRUE
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    connect-timeout: 5000

#日志
logging:
  level:
    java: off
    javax: off
    io: off
    sun: off
    _org: off
    reactor: off
    org.apache: off
    org.springframework: off
    org.mybatis: off